Explicit parent class used for ItemComponent vaadin/vaadin-list-box-flow#89
HasItemComponents.ItemComponent<T> is used. Otherwise NoClassDefFoundError is thrown on a class loading phase.

Web-component: vaadin-list-box